name: acoustics_repository
description: My new Dart package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies: 
  time_series_generator_api: 
    path: ../time_series_generator_api
  equatable: ^2.0.5
    
dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
